version: "3.8"
services:
  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "8080:80"
    networks:
      - my-network

  mysql-db:
    image: mysql:5.6
    container_name: blowfish-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: badcrud

    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro

networks:
  my-network:
    driver: bridge